<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>Microsoft.Azure.Batch.Samples.BatchMetricsUsageSample</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Microsoft.Azure.Batch.Samples.Common.csproj" />
    <ProjectReference Include="..\BatchMetrics\BatchMetrics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Compute.Batch" Version="1.0.0" />
    <PackageReference Include="Azure.ResourceManager.Batch" Version="1.6.0" />
  </ItemGroup>

</Project>
