--- 
jobs: 
  - 
    displayName: "Run lint tests"
    job: PythonTest
    pool: 
      vmImage: vs2017-win2016
    steps: 
      - 
        inputs: 
          versionSpec: $(python.version)
        task: UsePythonVersion@0
      - 
        script: |
            python -m pip install --upgrade setuptools
            python -m pip install -r $(System.DefaultWorkingDirectory)/Python/Batch/requirements.txt
            python -m pip install coveralls flake8 pytest pytest-cov requests_mock
            flake8 $(System.DefaultWorkingDirectory)/Python/Batch
    strategy: 
      matrix: 
        Python27: 
          python.version: "2.7"
        Python35: 
          python.version: "3.5"
        Python36: 
          python.version: "3.6"
  - 
    job: JavaTest
    pool: 
      vmImage: vs2017-win2016
    steps: 
      - 
        inputs: 
          goals: package
          javaHomeOption: JDKVersion
          jdkArchitectureOption: x64
          jdkVersionOption: "1.8"
          mavenOptions: "-Xmx3072m"
          mavenPomFile: $(System.DefaultWorkingDirectory)/Java/pom.xml
          publishJUnitResults: false
          testResultsFiles: "**/TEST-*.xml"
        task: Maven@3
pool: 
  vmImage: ubuntu-latest
trigger: 
  - master
