<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>Microsoft.Azure.Batch.Samples.MultiInstanceTasks</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MPIHelloWorld\**" />
    <Compile Remove="packages\**" />
    <Compile Remove="x64\**" />
    <EmbeddedResource Remove="MPIHelloWorld\**" />
    <EmbeddedResource Remove="packages\**" />
    <EmbeddedResource Remove="x64\**" />
    <None Remove="MPIHelloWorld\**" />
    <None Remove="packages\**" />
    <None Remove="x64\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Microsoft.Azure.Batch.Samples.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Compute.Batch" Version="1.0.0" />
    <PackageReference Include="Azure.ResourceManager.Batch" Version="1.6.0" />
  </ItemGroup>

</Project>
