<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Microsoft.Azure.Batch.Samples.JobManager</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Microsoft.Azure.Batch.Samples.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Compute.Batch" Version="1.0.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.24.0" />
  </ItemGroup>

</Project>