#!/usr/bin/env bash
#Command script to run pingpong performance testing on multiple machines as MPI task on Azure Batch.
#Usage: coordination-cmd

#For detail of MPI/RDMA, visit: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/classic/rdma-cluster

#prepare environment variables for intel mpi
