<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>Microsoft.Azure.Batch.Samples.BatchMetrics</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Compute.Batch" Version="1.0.0" />
  </ItemGroup>

</Project>
